### ISSUE TITLE
Missing information about cron/crontab configuration

### ISSUE THREAD

**Issue by tmotyl** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#121]
It should be described how to configure cron for TYPO3 on the server.

**Comment by linawolf** [comment]
@tmotyl  can you provide information? I think this depends on the server?

**Comment by garvinhicking** [comment]
I'm closing this older issue because I believe it is covered by "https://docs.typo3.org/c/typo3/cms-scheduler/main/en-us/Installation/CronJob/Index.html" - you'd normally stumble across this only when starting to setup scheduler, which is IMO beyond the scope of the installation/upgrade guide, hope that's ok (else, reopen! :))
