### ISSUE TITLE
doctrine/dbal v. 2.11.1 breaks typo3 compatibility with php version 7.2

### ISSUE THREAD

**Issue by michnhokn** [TYPO3-Documentation/TYPO3CMS-Guide-Installation#171]
Actually the new `"doctrine/dbal":  "2.11.1"` which is required by typo3/cms-core and typo3/cms-redirects (`"doctrine/dbal":  "^2.10"`) is breaking the compatibility with php version 7.2 because `doctrine/dbal` requires `php 7.3` in the new version.

There should be a fix for the new typo3 version which only allows `"doctrine/dbal": "1.10.*"` 

![image](https://user-images.githubusercontent.com/38752255/94415270-aa062000-017d-11eb-8500-8ca2160b2392.png)

**Comment by sypets** [comment]
Could you show what you did to run into this problem?

Because installing TYPO3 10 from scratch on a PHP 7.2 lets the version constraints get resolved just fine here:

```
php -v
PHP 7.2.33 (cli) 
```

```
composer create-project typo3/cms-base-distribution cms-base-distribution10
```

---

It uses doctrine/dbal **2.10.4**:

```
  - Installing doctrine/dbal (2.10.4): Downloading (100%)      
```

---

typo3/sysext/core has this as dependency:

```
		"doctrine/dbal": "^2.10",
```

which could result in 2.11.1, but it looks like 2.10.4 is being used, which is fine.

vendor/doctrine/dbal/composer.json:

```
 "require": {
        "php": "^7.2",

```

https://semver.mwl.be/#!?package=doctrine%2Fdbal&version=%5E2.10&minimum-stability=stable

**Comment by michnhokn** [comment]
@sypets After `composer update` the version number raised to 2.11.1 which is no loger compatible with PHP 7.2 [Release info DBAL](https://github.com/doctrine/dbal/releases/tag/2.11.0).

I temporarly fixed it by adding this requirement in my root composer.json:
```json
"require": {
    [...] // typo3 stuff
    "doctrine/dbal": "^1.10.0"
}
```

**Comment by michnhokn** [comment]
Alright, found the problem. Somehow im my setup the `"config"` option in `composer.json` is missing.

Don't forget to set the right plattform in config:
```json
"config": {
	"platform": {
		"php": "7.2"
	},
	"sort-packages": true
}
``` 

Thanks a lot @sypets.

**Comment by mbrodala** [comment]
The issue also won't occur if you really use PHP 7.2. If you use a higher version you allow packages to depend on this. In that case fixing the PHP version via `platform` might indeed help.
